openapi: 3.0.3
info:
  title: Notifications API
  description: API for managing user notifications
  version: 1.0.0

servers:
  - url: /api/v1

paths:
  /notifications:
    get:
      summary: List user's notifications
      operationId: listNotifications
      tags: [Notifications]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/PageNumber'
        - $ref: '#/components/parameters/PageSize'
        - name: unreadOnly
          in: query
          schema:
            type: boolean
            default: false
        - name: type
          in: query
          schema:
            $ref: '#/components/schemas/NotificationType'
      responses:
        '200':
          description: Paginated notification list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /notifications/unread-count:
    get:
      summary: Get unread notification count
      operationId: getUnreadCount
      tags: [Notifications]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Unread count
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnreadCountResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /notifications/{notificationId}:
    get:
      summary: Get notification details
      operationId: getNotification
      tags: [Notifications]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/NotificationId'
      responses:
        '200':
          description: Notification details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /notifications/{notificationId}/read:
    post:
      summary: Mark notification as read
      operationId: markAsRead
      tags: [Notifications]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/NotificationId'
      responses:
        '200':
          description: Notification marked as read
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /notifications/mark-all-read:
    post:
      summary: Mark all notifications as read
      operationId: markAllAsRead
      tags: [Notifications]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: All notifications marked as read
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarkAllReadResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /notifications/preferences:
    get:
      summary: Get notification preferences
      operationId: getNotificationPreferences
      tags: [Notifications]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User notification preferences
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationPreferencesResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
    patch:
      summary: Update notification preferences
      operationId: updateNotificationPreferences
      tags: [Notifications]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateNotificationPreferencesRequest'
      responses:
        '200':
          description: Updated preferences
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationPreferencesResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    NotificationId:
      name: notificationId
      in: path
      required: true
      schema:
        type: string
        format: uuid
    PageNumber:
      name: page
      in: query
      schema:
        type: integer
        minimum: 1
        default: 1
    PageSize:
      name: pageSize
      in: query
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20

  schemas:
    NotificationResponse:
      type: object
      required: [id, type, title, message, createdAt, isRead]
      properties:
        id:
          type: string
          format: uuid
        type:
          $ref: '#/components/schemas/NotificationType'
        title:
          type: string
        message:
          type: string
        entityType:
          type: string
          description: Related entity type (Client, Authorization, Transcript)
        entityId:
          type: string
          format: uuid
          description: Related entity ID for navigation
        channels:
          type: array
          items:
            $ref: '#/components/schemas/NotificationChannel'
        isRead:
          type: boolean
        readAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time

    NotificationListResponse:
      type: object
      required: [items, totalCount, page, pageSize, unreadCount]
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/NotificationResponse'
        totalCount:
          type: integer
        page:
          type: integer
        pageSize:
          type: integer
        unreadCount:
          type: integer

    UnreadCountResponse:
      type: object
      required: [count]
      properties:
        count:
          type: integer
        byType:
          type: object
          additionalProperties:
            type: integer
          example:
            AuthorizationSigned: 3
            AuthorizationExpiring: 2

    MarkAllReadResponse:
      type: object
      required: [markedCount]
      properties:
        markedCount:
          type: integer

    NotificationPreferencesResponse:
      type: object
      required: [emailEnabled, inAppEnabled]
      properties:
        emailEnabled:
          type: boolean
        inAppEnabled:
          type: boolean
        smsEnabled:
          type: boolean
          description: Future feature
        typePreferences:
          type: array
          items:
            $ref: '#/components/schemas/TypePreference'

    TypePreference:
      type: object
      required: [type, emailEnabled, inAppEnabled]
      properties:
        type:
          $ref: '#/components/schemas/NotificationType'
        emailEnabled:
          type: boolean
        inAppEnabled:
          type: boolean

    UpdateNotificationPreferencesRequest:
      type: object
      properties:
        emailEnabled:
          type: boolean
        inAppEnabled:
          type: boolean
        typePreferences:
          type: array
          items:
            $ref: '#/components/schemas/TypePreference'

    NotificationType:
      type: string
      enum:
        - AuthorizationSigned
        - AuthorizationExpiring
        - AuthorizationExpired
        - TranscriptUploaded
        - TeamInvitation
        - TeamMemberJoined

    NotificationChannel:
      type: string
      enum: [Email, InApp, Sms]

    ProblemDetails:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string

  responses:
    BadRequest:
      description: Invalid request
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    Unauthorized:
      description: Authentication required
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
    NotFound:
      description: Resource not found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
