import type { Metadata } from "next";
import localFont from "next/font/local";

import { Header } from "./views/shared/header";
import { Footer } from "./views/shared/footer";

import "bootstrap/dist/css/bootstrap.min.css";
import "../styles/styles.css";

const geistSans = localFont({
    src: "../fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "../fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <title>Jim Buttonow Tax Services</title>
                <link rel="stylesheet" href="css/styles.css" />
                <script src="js/dropscript.js " defer></script>
            </head>
            <body>
                <Header />
                <main className="main-content">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
